### ISSUE TITLE
Gradio patch should be dimension agnostic

### ISSUE THREAD

**Issue by John-WL** [John-WL/sd-webui-inpaint-difference#19]
Error message from https://github.com/John-WL/sd-webui-inpaint-difference/issues/4#issuecomment-1996211262:
```
Traceback (most recent call last):
  File "F:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "F:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1335, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "F:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\components\image.py", line 316, in postprocess        
    return processing_utils.encode_pil_to_base64(y)
  File "F:\stablediffusion\stable-diffusion-webui-1-8-0-rc\extensions\sd-webui-inpaint-difference\lib_inpaint_difference\gradio_hijack
s.py", line 13, in encode_pil_to_base64_new
    image_arr = np.asarray(pil_image)[:, :, ::-1]
IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed
```

The issue seems to be apparent when inpaint-diff and the [mosaic](https://github.com/Haoming02/sd-webui-mosaic-outpaint?tab=readme-ov-file) extension are used at the same time, though I believe the problem is more general than this conflict, and it should be fixed asap.

**Comment by John-WL** [comment]
Should be fixed now.
