### ISSUE TITLE
UI operation mode will conflict with other extensions' operation modes

### ISSUE THREAD

**Issue by John-WL** [John-WL/sd-webui-inpaint-difference#4]
Hijacking the UI to add an operation mode is not very clean, and it will conflict with other extensions that try to do the same. 
Adding operation modes in the UI is not very common among extensions in general though, so I don't think this is a big deal for now. 

Also, the next release of the Webui will potentially add a new load order feature, and this may help to solve the problem. 

The plan is to leverage the load order mechanism if possible on release. 
If it's still not enough, I'll have to take things into my own hands by either making a PR to the Webui, or publishing a small pip package to hijack uniformly the UI across extensions.

**Comment by John-WL** [comment]
Nvm, I just implemented it with a custom pip package

**Comment by clayne** [comment]
Attempted to use the [mosaic](https://github.com/Haoming02/sd-webui-mosaic-outpaint?tab=readme-ov-file) extension and ran into this... related?
```
Traceback (most recent call last):
  File "F:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "F:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1335, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "F:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\components\image.py", line 316, in postprocess        
    return processing_utils.encode_pil_to_base64(y)
  File "F:\stablediffusion\stable-diffusion-webui-1-8-0-rc\extensions\sd-webui-inpaint-difference\lib_inpaint_difference\gradio_hijack
s.py", line 13, in encode_pil_to_base64_new
    image_arr = np.asarray(pil_image)[:, :, ::-1]
IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed
```

Disabling this extension fixes it.

**Comment by John-WL** [comment]
Interesting, it is indeed related. I implemented a fix to make gradio run slightly faster for huge images a few months ago: https://github.com/John-WL/sd-webui-inpaint-difference/issues/15#issue-2075471228

This patch was recommended by a gradio dev (I pretty much copy-pasted from him): 
https://github.com/gradio-app/gradio/issues/2635#issuecomment-1423531319

I will update the code to make sure the conversion is dimension-agnostic. 
This should be its own issue, I will create a new one to track the bug.

**Comment by clayne** [comment]
Thanks for the quick response!

BTW: I also noticed it bombing out with "Just resize (latent upscale)". Not sure if its related but figured I'd mention it:

```
    Traceback (most recent call last):
      File "F:\stablediffusion\stable-diffusion-webui-1-8-0-rc\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "F:\stablediffusion\stable-diffusion-webui-1-8-0-rc\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "F:\stablediffusion\stable-diffusion-webui-1-8-0-rc\extensions\sd-webui-inpaint-difference\lib_inpaint_difference\webui_hijacks.py",
 line 30, in hijack_func
        return original_img2img_processing(id_task, mode, prompt, negative_prompt, prompt_styles, init_img, sketch,
      File "F:\stablediffusion\stable-diffusion-webui-1-8-0-rc\extensions\sd-webui-inpaint-background\lib_inpaint_background\webui_hijacks.py",
 line 28, in hijack_func
        return original_img2img_processing(id_task, mode, prompt, negative_prompt, prompt_styles, init_img, sketch,
      File "F:\stablediffusion\stable-diffusion-webui-1-8-0-rc\modules\img2img.py", line 234, in img2img
        processed = process_images(p)
      File "F:\stablediffusion\stable-diffusion-webui-1-8-0-rc\modules\processing.py", line 785, in process_images
        res = process_images_inner(p)
      File "F:\stablediffusion\stable-diffusion-webui-1-8-0-rc\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 59, in processing_
process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "F:\stablediffusion\stable-diffusion-webui-1-8-0-rc\modules\processing.py", line 855, in process_images_inner
        p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
      File "F:\stablediffusion\stable-diffusion-webui-1-8-0-rc\modules\processing.py", line 1581, in init
        image_masked.paste(image.convert("RGBA").convert("RGBa"), mask=ImageOps.invert(self.mask_for_overlay.convert('L')))
      File "F:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 1732, in paste
        self.im.paste(im, box, mask.im)
    ValueError: images do not match
```

All other modes work fine with different resize scales.

**Comment by John-WL** [comment]
This is not at all related, I get this error regardless of what extension is installed.
