### ISSUE TITLE
Extension does not load in latest A1111 version (dev branch)

### ISSUE THREAD

**Issue by Gushousekai195** [John-WL/sd-webui-inpaint-difference#7]
I updated my webui and now the extension does not load.

This is the error:
```*** Error executing callback after_component_callback for D:\AI\stable-diffusion-webui\extensions\sd-webui-inpaint-difference\lib_inpaint_difference\webui_callbacks.py
    Traceback (most recent call last):
      File "D:\AI\stable-diffusion-webui\modules\script_callbacks.py", line 248, in after_component_callback
        c.callback(component, **kwargs)
      File "D:\AI\stable-diffusion-webui\extensions\sd-webui-inpaint-difference\lib_inpaint_difference\img2img_tab_extender.py", line 45, in on_after_component
        cls.register_default_amount_of_tabs()
      File "D:\AI\stable-diffusion-webui\extensions\sd-webui-inpaint-difference\lib_inpaint_difference\img2img_tab_extender.py", line 67, in register_default_amount_of_tabs
        for child in cls.img2img_tabs_block.children
    AttributeError: 'NoneType' object has no attribute 'children'

---```

**Comment by John-WL** [comment]
Are you using the extension on the dev branch of A1111 Webui?

**Comment by John-WL** [comment]
I just tried the extension on the dev branch, I don't think I can reproduce. Could it be a conflict between multiple extensions?

**Comment by Gushousekai195** [comment]
> I just tried the extension on the dev branch, I don't think I can reproduce. Could it be a conflict between multiple extensions?

I also disabled all the other extensions I've installed, but left this extension enabled. The error still happens.

**Comment by John-WL** [comment]
I was able to reproduce, thank you for the help :)
Should be fixed now.
